/**
 * The NIC product-category catalogue, and the search behind the picker.
 *
 * 1,846 rows out of `NIC_Codes_Updated.pdf`, regenerated by
 * `scripts/nic-pdf-to-csv.py` — that script is the only thing that should ever
 * write `src/data/nicCodes.json`, and its docstring explains why the codes in
 * the PDF cannot be used as printed (the export lost every leading zero, so
 * "014 Animal production" and "14 Manufacture of wearing apparel" are both
 * printed as "14"; 34 codes collide that way). The zeros are restored, so a
 * code here identifies exactly one category.
 *
 * LOADED ON DEMAND. The dataset is ~155 KB and belongs to one field on one
 * form. `import()` puts it in its own chunk, fetched the first time somebody
 * opens the picker, so it costs nothing on every other page of the site.
 */

/** A row as stored — short keys, because this is shipped to a browser. */
interface CompactRow {
    /** NIC code, zero-padded: 2 division, 3 group, 4 class, 5 sub-class. */
    c: string;
    /** The NIC description. */
    d: string;
    /** Industry type: `M` manufacturing, `S` service. */
    t: string;
}

export interface NicCategory {
    code: string;
    description: string;
    /** 'Manufacturing' | 'Service' */
    industryType: string;
    /** 'Division' | 'Group' | 'Class' | 'Sub-class' — derived from the code. */
    level: string;
}

/**
 * What a company stores against itself.
 *
 * `code` is `''` for a category the member typed that NIC does not list. That
 * is deliberate and is why this is not an enum anywhere: the dataset is a good
 * reference, not a census, and a real product it does not name must still be
 * recordable. The same reasoning as the `+` on `RegionInput` — see
 * ADMIN-FIRST REGION ARCHITECTURE in CLAUDE.md.
 */
export interface ProductCategory {
    code: string;
    description: string;
    industryType: string;
}

const LEVELS: Record<number, string> = {
    2: 'Division',
    3: 'Group',
    4: 'Class',
    5: 'Sub-class',
};

let cache: NicCategory[] | null = null;
let inFlight: Promise<NicCategory[]> | null = null;

/**
 * The catalogue, fetched once per session.
 *
 * `inFlight` is held as well as `cache` because the picker mounts and the input
 * is focused in the same tick on a fast machine: two calls before the first
 * resolves would fetch and parse 155 KB twice.
 */
export const loadNicCategories = (): Promise<NicCategory[]> => {
    if (cache) return Promise.resolve(cache);
    if (inFlight) return inFlight;

    inFlight = import('@/data/nicCodes.json')
        .then((module) => {
            const rows = ((module.default || module) as unknown as CompactRow[]) || [];
            cache = rows.map((row) => ({
                code: row.c,
                description: row.d,
                industryType: row.t === 'M' ? 'Manufacturing' : 'Service',
                level: LEVELS[String(row.c || '').length] || 'Sub-class',
            }));
            return cache;
        })
        .catch((error) => {
            // Reset so a later attempt can retry — a dropped connection must not
            // leave the picker permanently empty for the rest of the session.
            inFlight = null;
            console.warn('Could not load the NIC category list:', error);
            return [];
        });

    return inFlight;
};

/** Lower-cased, whitespace-collapsed. Every comparison goes through this. */
const norm = (value: unknown): string =>
    String(value ?? '').toLowerCase().replace(/\s+/g, ' ').trim();

/**
 * Search the catalogue.
 *
 * EVERY token has to match, so "rice mill" narrows rather than widening — the
 * usual failing of a plain `includes()` search is that a second word makes the
 * result set bigger, which reads as the filter being broken.
 *
 * A numeric query is matched against the CODE as a prefix, so a member who
 * knows their NIC code types it directly. It is also still matched against the
 * description, because a description can contain a number.
 *
 * Ranked best-first:
 *   0  the description starts with the query
 *   1  a word in the description starts with the query
 *   2  the code starts with the query
 *   3  the description merely contains it
 *
 * then broad before specific, so "wearing apparel" leads with the division and
 * walks down to the sub-classes rather than opening on row 900 of the file.
 */
export const searchNicCategories = (
    catalogue: NicCategory[],
    query: string,
    limit = 50,
): { results: NicCategory[]; total: number } => {
    const q = norm(query);
    if (!q) return { results: [], total: 0 };

    const tokens = q.split(' ').filter(Boolean);
    const scored: { row: NicCategory; rank: number }[] = [];

    for (const row of catalogue) {
        const desc = norm(row.description);
        const code = row.code;

        const matches = tokens.every(
            (token) => desc.includes(token) || code.startsWith(token),
        );
        if (!matches) continue;

        let rank = 3;
        if (desc.startsWith(q)) rank = 0;
        else if (new RegExp(`\\b${q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`).test(desc)) rank = 1;
        else if (code.startsWith(q)) rank = 2;

        scored.push({ row, rank });
    }

    scored.sort((a, b) =>
        a.rank - b.rank
        || a.row.code.length - b.row.code.length
        || a.row.code.localeCompare(b.row.code));

    return {
        results: scored.slice(0, limit).map((s) => s.row),
        total: scored.length,
    };
};

/** Is this exact description already in the catalogue? Drives the "add" row. */
export const isKnownDescription = (catalogue: NicCategory[], query: string): boolean => {
    const q = norm(query);
    return catalogue.some((row) => norm(row.description) === q);
};

/** How a stored category reads on one line. */
export const categoryLabel = (category: ProductCategory): string =>
    category.code ? `${category.code} — ${category.description}` : category.description;

/** Two stored categories are the same if the code matches, or the text does. */
export const sameCategory = (a: ProductCategory, b: ProductCategory): boolean =>
    (a.code && b.code)
        ? a.code === b.code
        : norm(a.description) === norm(b.description);
